name: Build and deploy Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
    # - cron: "0 * * * *" # stündlich
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch Google Sheet and build JSON
        run: node scripts/fetch-data.mjs

      - name: Upload calendar artifact
        uses: actions/upload-artifact@v4
        with:
          name: calendar
          path: docs/calendar.ics

      - name: Upload original calendar artifact
        uses: actions/upload-artifact@v4
        with:
          name: calendar-original
          path: docs/calendar-original.ics

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4